safe:                false
# Permalinks
permalink:           pretty

# Setup
title:               imkaiel.
tagline:             Welcome.
url:                 http://imkaiel.github.io/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Karl Pineda
  url:               http://imkaiel.github.io/
  email:             kmpineda22@gmail.com

# Custom vars
version:             2.0.0-custom
github:
  repo:              https://github.com/poole/poole

jekyll_timeago:
  depth:             1 # Level of detail

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-timeago
